In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.6.0+cu124


In [ ]:
# To create tensors we use 'torch.tensor'
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim  ## dimensions of a scalar is 0


0

In [ ]:
## get tensor as a python int
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[6,8],[3,5]])
MATRIX

tensor([[6, 8],
        [3, 5]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0] # 0th element in the matrix

tensor([6, 8])

In [ ]:
MATRIX[1] # 1st element in the matrix

tensor([3, 5])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,3,4,6],
                        [4,7,8,2],
                        [7,6,5,1]]])
TENSOR

tensor([[[1, 3, 4, 6],
         [4, 7, 8, 2],
         [7, 6, 5, 1]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 4])

 **Scalar , vector uses lower case variables.
    MATRIX and TENSOR uses UPPER CASE variables**

**RANDOM NUMBERS**

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers in a better way to represent the data.

It goes like

Start with random numbers -> look at the data -> update random numbers -> look at the data ->update random numbers


Torch random tensors - https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3705, 0.9499, 0.7892, 0.6642],
        [0.3929, 0.0548, 0.3316, 0.1379],
        [0.0513, 0.5437, 0.6872, 0.5122]])

In [ ]:
random_tensor.ndim

2

**Zeros and ones**

In [ ]:
Zeros = torch.zeros(3,4)
Zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
Ones = torch.ones(5,3)
Ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
### We can multiply these tensors
random_tensor * Zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
Ones.dtype  ## to check data type of tensors

torch.float32

***Creating range of tensors and tensors-like***

In [ ]:
torch.range(0,10)

/tmp/ipython-input-397-497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_to_nine = torch.arange(start=0,end=100,step=15)
one_to_nine

tensor([ 0, 15, 30, 45, 60, 75, 90])

In [ ]:
## Tensors-Like  If you want to create a tensor in a shape of other tensor
new_tensor = torch.zeros_like(input =one_to_nine)
new_tensor

tensor([0, 0, 0, 0, 0, 0, 0])

**TENSOR DATATYPES**

**Note** : Tensor datatypes is one of the 3 big errors you will face in PyTorch and DeepLearning

1.Tensors not in right datatype (**Some times different data type might not throw an error but this is something we should always take into consideration**)

2.Tensors not in right shape (**If we multiply or add two tensors with different shape we will run into error**)

3.Tensors not in right device (**If we do anything with two tensors but both are in different devices like CPU, GPU then its an error**)

In [ ]:
float_32_tensor = torch.tensor ([3.0,4.0,7.0],
                                dtype= None,
                                device=None,
                                requires_grad=False)

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# Changing the tensor datatype
float_16_tensor = float_32_tensor.type(torch.float64) #simply use the type() function
float_16_tensor

tensor([3., 4., 7.], dtype=torch.float64)

**FINDING OUT INFORMATION ABOUT THE TENSOR**

Just use the inbuilt functions to get information about each tensors

In [ ]:
print(f"Device tensor is on is : {float_16_tensor.device}")
print(f"Shape of the tensor is : {float_16_tensor.shape}")

Device tensor is on is : cpu
Shape of the tensor is : torch.Size([3])


**MANIPULATING TENSORS (TENSOR OPERATIONS)**



*   1.Addition
*  2.Subtraction
*   3.Multiplication (Element-wise)
*   4.Division
*  5.Matrix Multiplication

In [ ]:
##Element-wise Multiplication
new_tensor = torch.tensor([1,2,3])
print (new_tensor,"*",new_tensor)
print(f"Answer : {new_tensor*new_tensor}")  # Each element is multiplied with each element


tensor([1, 2, 3]) * tensor([1, 2, 3])
Answer : tensor([1, 4, 9])


In [ ]:
#Matric Multiplication
torch.matmul(new_tensor,new_tensor)

tensor(14)

Two main ways of performing multiplication in neural networks and deep learning are **Element-wise Multiplication** and **Matrix Multiplication (Dot product)**

There are two main rules should be satisfied while performing matrix multiplication:

1. The **The inner dimensions must match**

*  (3,2) @ (2,3) will work      @ means multiplication
*  (2,3) @ (2,3) will not work
*  (2,3) @ (3,2) will work

2. The resulting matrix has the shape of the **outer dimension**
  
*   (3,2) @ (2,3) -> The resulting matrix will have (3,3) dimension
*   (2,3) @ (3,2) -> The resulting matrix will have (2,2) dimension


**# RULE - 1**

torch.matmul(torch.rand(3,3),torch.rand(2,3))

**This will give an error coz inner dimensions doesn't match**

In [ ]:
#RULE - 2
torch.matmul(torch.rand(3,2),torch.rand(2,3)) # This will give a 3,3 matrix

tensor([[0.8799, 0.6633, 0.2985],
        [0.4443, 0.4424, 0.8164],
        [0.7543, 0.6614, 0.8303]])

**MATRIX - TRANSPOSE**

When we have different inner dimensions, matrix multiplication is not possible.
So, we **transpose the matrix** and do the matrix multiplication.

In [ ]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[1,2,3],
                        [3,4,5]])
# Here tensor_A is a (3,2) matrix and tensor_B is a (3,3) matrix

# The inner dimensions does not match, so we transpose

tensor_B = tensor_B.T

# After transposing it becomes(2,3) matrix

print(f"Shape of tensor_A : {tensor_A.shape}")
print(f"Shape of tensor_A : {tensor_B.T.shape}")

print(f"\n Output : {torch.mm(tensor_A,tensor_B.T)}")  ## torch.mm is alias for torch.matmul

Shape of tensor_A : torch.Size([3, 2])
Shape of tensor_A : torch.Size([2, 3])

 Output : tensor([[ 7, 10, 13],
        [15, 22, 29],
        [23, 34, 45]])


**FINDING MIN,MAX,MEAN,SUM - TENSOR AGGREGATION**

In [ ]:
x=torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
print(f" Minimum value in x : {torch.min(x)}") # also we can use x.min()
print(f" Maximum value in x : {torch.max(x)}") # also we can use x.max()

 Minimum value in x : 1
 Maximum value in x : 91


In [ ]:
#First we need to change the datatype of x
# torch.mean() function works with float32 tensor datatype
print(f"Datatype of x :{ x.dtype}")
x_1 = x.type(torch.float32) # Here we are changing the datatype
print(f" \nConverted datatype of x :{ x_1.dtype}")
print(f" \nMean/Average value of x : {torch.mean(x_1)}")  # also we can use x.mean()

Datatype of x :torch.int64
 
Converted datatype of x :torch.float32
 
Mean/Average value of x : 46.0


**Finding the position of the arguments**

In [ ]:
x=torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
print(f" Position of the maximum value in x : {torch.argmax(x)}") # also we can use x.argmax()
print(f" Position of the minimum value in x : {torch.argmin(x)}") # also we can use x.argmin()


 Position of the maximum value in x : 9
 Position of the minimum value in x : 0


# Reshaping,stacking,squeezing and unsqueezing tensors




*  Reshaping - reshapes an input tensor to a defined shape
*  View - Returns a view of an input tensor of a certain shape but reatins the same memory as original tensor
*    Stacking - Combine multiple tensors on top of eachother (vstack) or side by side (hstack)

*   Squeeze - removes all '1' dimensions from a tensor
*   Unsqueeze - Adds '1' dimension to a tensor

*   Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


So, Basically manipulating the tensors



In [ ]:
 # create a new tensor
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(9,1) # this will only work if the diemensions are direct multiples of the original tensor
x_reshaped,x_reshaped.shape # the resulting shape is the original tensor's shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
z=x.view(1,9)
print(f"this is z : {z}")
print(f"this is x : {x}") # Both x and z are same now because they both share same memory

this is z : tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
this is x : tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
# Stacking tensors on top of eachother (vstack)
x_stacked=torch.hstack([x,x,x,x,x,x,x,x,x])
x_stacked

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9.])

A PyTorch tensor's shape defines how data is organized — like its “structure” or “layout.”
But if a dimension has size 1, it doesn't add any real data — it’s just like empty wrapping.

squeeze() removes these meaningless dimensions.

In [ ]:
print(f"Previous tensor shape : {x_reshaped.shape}")

Previous tensor shape : torch.Size([9, 1])


In [ ]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
print(f"Squeezed tensor shape : {x_reshaped.squeeze().shape}")

Squeezed tensor shape : torch.Size([9])


In [ ]:
# We give parameters in unsqueeze function, the parameter is dim and this decides the position

# if we say dim= 0 , '1' will be added at 0th position of the tensor
# if we say dim= 1 , '1' will be added at 1st position of the tensor
# if we say dim= 2 , '1' will be added at 2nd position of the tensor
newyy=torch.rand(3,4)
newyy.shape


torch.Size([3, 4])

If shape is [A, B, C], then:

-3 means index 0 → A

-2 means index 1 → B

-1 means index 2 → C

**Here 'dim' literally means the position**

In [ ]:
print(f"Unsqueezed newyy shape : {newyy.unsqueeze(dim=-2).shape}")
print(f"Unsqueezed newyy shape : {newyy.unsqueeze(dim=-1).shape}")
print(f"Unsqueezed newyy shape : {newyy.unsqueeze(dim=-3).shape}")

Unsqueezed newyy shape : torch.Size([3, 1, 4])
Unsqueezed newyy shape : torch.Size([3, 4, 1])
Unsqueezed newyy shape : torch.Size([1, 3, 4])


In [ ]:
# torch.permute -> This changes the dimensions(i.e Positions)

tensy = torch.randn(5,3,2)
tensy

tensor([[[-0.4239,  0.6745],
         [ 0.2639, -0.2453],
         [-0.9004,  0.2850]],

        [[-1.1884,  1.2437],
         [-1.0652, -0.6124],
         [ 0.2942, -1.6012]],

        [[-0.1349,  1.7208],
         [-1.1490,  1.1407],
         [ 1.2066, -1.9752]],

        [[-0.7208,  0.6759],
         [ 0.2481, -0.7597],
         [ 0.4213, -0.3075]],

        [[-1.3787,  0.6238],
         [-0.2048, -1.9138],
         [-1.0335,  0.4070]]])

In [ ]:
torch.permute(tensy,(2,0,1))

tensor([[[-0.4239,  0.2639, -0.9004],
         [-1.1884, -1.0652,  0.2942],
         [-0.1349, -1.1490,  1.2066],
         [-0.7208,  0.2481,  0.4213],
         [-1.3787, -0.2048, -1.0335]],

        [[ 0.6745, -0.2453,  0.2850],
         [ 1.2437, -0.6124, -1.6012],
         [ 1.7208,  1.1407, -1.9752],
         [ 0.6759, -0.7597, -0.3075],
         [ 0.6238, -1.9138,  0.4070]]])

In [ ]:
torch.permute(tensy,(2,0,1)).size
#tensy = torch.randn(5,3,2)
# here after permuting the positions changes (2,5,3) so now we got 2 matrices with 5 rows and 3 columns

<function Tensor.size>

In [ ]:
tensy[0,0,0] = 8928932
permuted =torch.permute(tensy,(2,0,1))
permuted[0,0,0] # the value 8928932 is now assigned to permuted also


tensor(8928932.)

In [ ]:
#Indexing in Pytorch is same like indexing in Numpy
tensy

tensor([[[ 8.9289e+06,  6.7448e-01],
         [ 2.6388e-01, -2.4526e-01],
         [-9.0042e-01,  2.8495e-01]],

        [[-1.1884e+00,  1.2437e+00],
         [-1.0652e+00, -6.1235e-01],
         [ 2.9419e-01, -1.6012e+00]],

        [[-1.3489e-01,  1.7208e+00],
         [-1.1490e+00,  1.1407e+00],
         [ 1.2066e+00, -1.9752e+00]],

        [[-7.2080e-01,  6.7586e-01],
         [ 2.4808e-01, -7.5972e-01],
         [ 4.2129e-01, -3.0754e-01]],

        [[-1.3787e+00,  6.2383e-01],
         [-2.0482e-01, -1.9138e+00],
         [-1.0335e+00,  4.0704e-01]]])

In [ ]:
tensy[3][2][0]  # 3rd matrix 2nd position and 0th element

tensor(0.4213)

In [ ]:
tensy[4][1][1]  # 4th matrix 1st position and 0th element
# the element is rounded off

tensor(-1.9138)

In [ ]:
#tensy[3][2][3] #index 3 is out of bounds for dimension 0 with size 2

In [ ]:
 tensor_new =torch.tensor([[[2,4,5],
                [6,7,8],
                [12,14,1]]])
 tensor_new

tensor([[[ 2,  4,  5],
         [ 6,  7,  8],
         [12, 14,  1]]])

In [ ]:
tensor_new [0][0][1]

tensor(4)

In [ ]:
tensor_new [0][0][2]

tensor(5)